"""auto-vote

Revision ID: 1ca7db6062d2
Revises: 956788dabd4b
Create Date: 2026-04-21 21:55:49.691703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca7db6062d2'
down_revision: Union[str, Sequence[str], None] = '956788dabd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE posts ADD COLUMN IF NOT EXISTS content VARCHAR")

    op.execute("UPDATE posts SET content = '' WHERE content IS NULL")

    op.execute("ALTER TABLE posts ALTER COLUMN content SET NOT NULL")

    op.alter_column(
        'posts',
        'owner_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
